rust analyzer snake_case fix #2882
rustwasm/wasm-bindgen pull request #3138
Opened 2022-11-06 21:58 UTC by eli-front

Fixes #2882

2022-11-07 11:51 UTC, Liamolucko requested changes

2022-11-11 21:16 UTC, Liamolucko commented on crates/backend/src/codegen.rs
> +                #[link(wasm_import_module = "__WBINDGEN_PLACEHOLDER__")]
This also needs to remain lowercase.

2022-11-14 11:35 UTC, Liamolucko commented on crates/backend/src/codegen.rs
> +        );
The CLI also relies on this being lowercase.

```suggestion
        let name = Ident::new(&format!("__wbindgen_describe_{}", ident), ident.span());
```

2022-11-14 11:35 UTC, Liamolucko commented on crates/test/src/rt/browser.rs
> +    static DOCUMENT: HTMLDocument;
This still needs to be lowercase on the JS side:

```suggestion
    #[wasm_bindgen(js_name = document)]
    static DOCUMENT: HTMLDocument;
```

2022-11-14 16:50 UTC, eli-front commented
Thanks to @Liamolucko We have passed all CI tests!

2022-12-15 20:51 UTC, FrankReh commented
Any maintainers can review this?

2022-12-15 23:21 UTC, Liamolucko commented
Sorry, I completely let this slip. In the meantime, though, I found out that it's actually possible to not give consts names at all, by naming them `_`. I think that's a better solution, since it also makes it impossible for the consts to cause name collisions, so I opened #3198 which does that instead.

2022-12-15 23:31 UTC, eli-front commented
> Sorry, I completely let this slip. In the meantime, though, I found out that it's actually possible to not give consts names at all, by naming them `_`. I think that's a better solution, since it also makes it impossible for the consts to cause name collisions, so I opened #3198 which does that instead.

What was the original value for naming the constants?

2022-12-15 23:40 UTC, Liamolucko commented
> What was the original value for naming the constants?

I don't think there was any, I think it was just that nobody knew you didn't have to give them names.

2022-12-16 01:19 UTC, closed without merging