Add WebIDLs for Filesystem Access API
rustwasm/wasm-bindgen pull request #3327
Opened 2023-02-23 17:59 UTC by Speak2Erase

[IDL](https://fs.spec.whatwg.org/), [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API)

**I'm pretty new to contributing to projects like this, please lmk if I did something wrong!**

I followed the basic instructions listed in `web-sys`'s Readme. 

As far as I can tell, the bindings are correct. However, I don't really know what I am doing, *especially* about `[Throws]`, so that assumption could be wrong.

The Filesystem Access API seems to be pretty stable, however some browsers do not support it (i.e. Firefox) so I added it to unstable.

2023-05-11 12:55 UTC, daxpedda requested changes
LGTM otherwise.
Needs a rebase though.

2023-05-14 21:58 UTC, djozis commented
Hopefully not a faux pas, but I wanted this too, including the PR feedback, so I made the changes for my personal use, and thought I'd offer it back here: #3427

2023-05-15 16:50 UTC, daxpedda commented
Closing in favor of #3427.

2023-05-15 16:50 UTC, closed without merging

2023-05-17 02:20 UTC, djozis commented on crates/web-sys/webidls/unstable/FilesystemAccess.webidl
> +  Promise<undefined> truncate(unsigned long long size);
I created a PR for this, can continue discussion there perhaps: #3435