Add async variants of Atomics.wait
rustwasm/wasm-bindgen pull request #3504
Opened 2023-07-04 12:51 UTC by allsey87

`Atomics.waitAsync` now has reasonable [support in most browsers](https://caniuse.com/mdn-javascript_builtins_atomics_waitasync) with Firefox being the notable exception, however they have a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1467846) for implementing it.

I used the binding for `Atomics.wait` as a reference and one thing that seems off to me is that the `typed_array` argument for the bigint varieties of these functions take an `Int32Array`, instead of a `BigInt64Array`/`BigUint64Array`. It seems to me that the most correct thing to do here is two make further variants of this function, e.g., add the `*_biguint` variants, which also take u64 as their value argument. If there is a consensus on this, I can add the variants and we can rename this PR to something like "Clean up Atomics.wait and Atomics.waitAsync".

2023-07-04 13:08 UTC, allsey87 commented
Actually, at least according to the docs that I can find, `BigUintArray` is not supported, only `BigIntArray`.

2023-07-05 12:06 UTC, daxpedda requested changes
I don't know what happened here, but I would argue that the current `wait_bigint` functions are just wrong, they should take a `BigInt64Array` instead of a `Int32Array`.

But I think we don't need to add to that any further.
Also we could definitely remove the documentation around `BigUint64Array`.

2023-07-05 12:06 UTC, daxpedda commented on crates/js-sys/src/lib.rs
> +            typed_array: &Int32Array,
```suggestion
            typed_array: &BigInt64Array,
```

2023-07-05 12:06 UTC, daxpedda commented on crates/js-sys/src/lib.rs
> +            typed_array: &Int32Array,
```suggestion
            typed_array: &BigInt64Array,
```

2023-07-05 12:52 UTC, daxpedda approved these changes
Thanks!

2023-07-05 13:03 UTC, daxpedda commented
I was thinking about using this here:
https://github.com/rustwasm/wasm-bindgen/blob/29205c51b0d617ec6fef17df859e7ac4429746bb/crates/futures/src/task/multithread.rs#L189-L190

But it wouldn't help much because we need the binding to detect support anyway. We also want to have the custom return type to avoid the overhead of `Reflect`, something we won't add in `js-sys` because we don't do this in general there.

2023-07-05 13:04 UTC, merged

2023-07-05 14:14 UTC, allsey87 commented
> But it wouldn't help much because we need the binding to detect support anyway. We also want to have the custom return type to avoid the overhead of `Reflect`, something we won't add in `js-sys` because we don't do this in general there.

Yep, I was thinking that/stumbled across that when I was checking whether `waitAsync` was already implemented.

Regarding the non-async variants of `wait`, shall I put together a PR that fixes `type_array` for the `_bigint` variants? It would be a breaking change, although I guess no one is using this API...

2023-07-05 17:41 UTC, hamza1311 commented
I'm fine with such breaking changes. It won't be the first time we made breaking changes to API that no one is/should be using ([as an example, removing interface types comes to mind](https://github.com/rustwasm/wasm-bindgen/pull/3372))