feat: add RTCDataChannel id
rustwasm/wasm-bindgen pull request #3547
Opened 2023-08-04 17:58 UTC by DougAnderson444

Adds [`RTCDataChannel` readonly attribute `id`](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/id)

Set as type `unsigned short` compiles to `u16` which is the size of `id` (`0` to `65,534`)

fixes https://github.com/rustwasm/wasm-bindgen/issues/3542

2023-08-04 18:29 UTC, DougAnderson444 commented
I don't understand what I did wrong to upset the `git diff` step, all the generated code looks fine

2023-08-04 18:35 UTC, DougAnderson444 commented
When I run the `cargo run --release --package wasm-bindgen-webidl -- webidls src/features ./Cargo.toml` command (Windows 10), I do get a rust fmt error:

```bash
Error: rustfmt failed

Caused by:
    The filename or extension is too long. (os error 206)
```

2023-08-04 23:05 UTC, daxpedda requested changes
You should never modify the generated files yourself, only modify the WebIDL and then let the generator run.

I'm not sure what the issue is you are running into when running the WebIDL generator, it might be Windows specific, unfortunately I don't have access to a Windows machine right now. It would actually be nice if you can look into it and potentially fix it, but that's a matter for a separate PR.

Feel free to ping me if you don't get the generator to work and I can run it for you.

2023-08-05 13:21 UTC, DougAnderson444 commented
> You should never modify the generated files yourself, only modify the WebIDL and then let the generator run.

I thought I did that :/ 

> I'm not sure what the issue is you are running into when running the WebIDL generator, it might be Windows specific, 

I'm not sure about this being a Windows issue anymore, because I just committed your suggestion, CI ran the generator, and `git diff --exit-code` still didn't pass. I see the generated code changed from `u16` to `Option<u16>` so that looks right.  So that shouldn't have anything to do with Windows, right?

> Feel free to ping me if you don't get the generator to work and I can run it for you.

Yes please do, I'm getting frustrated as I don't really know what to try next. I didn't think adding one line would be so involved! 😐

2023-08-05 13:25 UTC, daxpedda commented
> > I'm not sure what the issue is you are running into when running the WebIDL generator, it might be Windows specific,
> 
> I'm not sure about this being a Windows issue anymore, because I just committed your suggestion, CI ran the generator, and `git diff --exit-code` still didn't pass. I see the generated code changed from `u16` to `Option<u16>` so that looks right. So that shouldn't have anything to do with Windows, right?

Ah, apologies, I thought you did it by hand instead of running the generator.
I think the generator has a different output on Windows actually ... so looks like a bug to me.

> > Feel free to ping me if you don't get the generator to work and I can run it for you.
> 
> Yes please do, I'm getting frustrated as I don't really know what to try next. I didn't think adding one line would be so involved! neutral_face

No problem, it seems the generator runs correctly for me. Don't let this stop you from contributing though, I'm happy to fix this up in the future as well :wink:.

2023-08-05 13:42 UTC, DougAnderson444 commented
Oh for sure I'm happy to help with open source, I love it 😁

Thanks for all your help

2023-08-05 18:54 UTC, merged