fix: Optional JSDoc `@param`
rustwasm/wasm-bindgen pull request #3577
Opened 2023-08-28 16:00 UTC by magic-akari

- fix #3576

2023-08-28 20:25 UTC, daxpedda requested changes
Could you add a note in the changelog?
Otherwise looks great!

2023-08-28 23:17 UTC, Liamolucko commented
An issue I can see here is that this will currently produce optional parameters before required parameters; e.g. this function:

```rs
#[wasm_bindgen]
pub fn foo(a: Option<i32>, b: i32) {}
```

generates this JSDoc:
```js
/**
* @param {number | undefined} [a]
* @param {number} b
*/
```

`a` is marked as optional even though `b` is required, so it's impossible to actually leave it out.

I wasn't sure if this actually mattered, but it seems like it does because TypeScript complains about it:

```
test.js(5,17): error TS1016: A required parameter cannot follow an optional parameter.
```

2023-08-29 01:08 UTC, magic-akari commented
> An issue I can see here is that this will currently produce optional parameters before required parameters; e.g. this function:

@Liamolucko You are right. I think it should be handled by reversing the order like typescript_signature.

2023-08-29 07:22 UTC, daxpedda commented on CHANGELOG.md
> +* Fixed Optional parameters in JSDoc
```suggestion
* Fixed optional parameters in JSDoc.
```

2023-08-29 07:23 UTC, daxpedda approved these changes
LGTM!
Thanks @Liamolucko for catching that.

2023-08-29 07:59 UTC, merged