feat: add new web lock api interface
rustwasm/wasm-bindgen pull request #3604
Opened 2023-09-10 09:29 UTC by Solo-steven

fix issue #3456.
this is the first time I have contributed to this repo, If there is some definition that is wrong, please tell me! thanks ~

2023-09-11 08:26 UTC, daxpedda requested changes
Not sure exactly what happened here, did you check the CI failure?
Could you take a look at [the documentation](https://github.com/rustwasm/wasm-bindgen/blob/main/guide/src/contributing/web-sys/supporting-more-web-apis.md) and see if that generates the code correctly?

- Looking at the [reference](https://w3c.github.io/web-locks/#idl-index) there are a couple of APIs still missing.
- A changelog entry is missing.

It would also be nice if you link your sources. E.g. double-checking the [Mozilla implementation](https://hg.mozilla.org/mozilla-central/file/e91d172728590586e38bc431f3dc779479e365d5/dom/webidl/LockManager.webidl) to see if any functions are throwing.

Otherwise LGTM!

2023-09-13 05:08 UTC, Solo-steven commented
Hi @daxpedda, thanks for your review, It is my fault that I wrote the `gen_*` file instead of using the auto codegen command, Now I have switched to auto codegen, and All the CI tests are passed.
Since MDN only have `LockManager` and `Lock` document, I only add the MDN link to `gen_lock` and `gen_lockManager`, if there is any wrong, please tell me ~ thanks ~

2023-09-13 08:14 UTC, daxpedda commented
> Since MDN only have `LockManager` and `Lock` document, I only add the MDN link to `gen_lock` and `gen_lockManager`, if there is any wrong, please tell me ~ thanks ~

I only meant posting it here in the issue! But that's for the next time, I already got the links and posted them above :wink:.

2023-09-13 08:15 UTC, daxpedda requested changes
LGTM!
Changelog entry is missing.

2023-09-16 05:18 UTC, Solo-steven commented
Hi @daxpedda thanks for your reply, but I can't find the document about adding Changelog, could you help me find the link to the document or give me some simple instructions? thanks ~ ( and sorry for bother you again )

2023-09-16 06:37 UTC, Solo-steven commented
Hi @daxpedda  thanks for the reminder, I added the entry to the changelog, if the entry description is not correct, please tell me, thanks ~

2023-09-16 18:29 UTC, daxpedda commented on CHANGELOG.md
> +* Add bindings for `WebLock` related api to `web-sys`.
```suggestion
* Add bindings for the Web Locks API to `web-sys`.
```

2023-09-16 18:30 UTC, daxpedda approved these changes
Thanks!

2023-09-16 18:30 UTC, merged