Updated Notification APIs
rustwasm/wasm-bindgen pull request #3667
Opened 2023-10-24 04:40 UTC by maccesch

2023-10-24 05:57 UTC, maccesch commented
I don't exactly understand why this on check didn't go through. I followed the contribution guidelines. What can I do to fix this?

2023-10-24 09:18 UTC, daxpedda commented
This is just missing the `Cargo.toml` adjustments, looking at the CI results you can easily see what needs to be done:
```diff
--- a/crates/web-sys/Cargo.toml
+++ b/crates/web-sys/Cargo.toml
@@ -880,6 +880,7 @@ NodeFilter = []
 NodeIterator = []
 NodeList = []
 Notification = ["EventTarget"]
+NotificationAction = []
 NotificationBehavior = []
 NotificationDirection = []
 NotificationEvent = ["Event", "ExtendableEvent"]
```
> I don't exactly understand why this on check didn't go through. I followed the contribution guidelines. What can I do to fix this?

You probably forgot to point the tool towards the `Cargo.toml` file. The issue is that the book isn't updated, but you find the updated version here: https://rustwasm.github.io/wasm-bindgen/contributing/web-sys/supporting-more-web-apis.html.
Note the last argument `./Cargo.toml`.

2023-10-24 20:42 UTC, maccesch commented
I replaced the whole idl file now with the latest spec from that link. I hope that's ok? It makes some breaking changes but the previous version of the notification API seems to have been very old.

2023-10-25 08:21 UTC, daxpedda requested changes
Unfortunately we can't just correct the API like this because that would require a breaking change.

I think removing `GetNotificationOptions`, `NotificationBehavior` and `Notification.get()` is fine though because they don't actually exist anymore. @Liamolucko and @hamza1311 would you be fine with that as well?

Could you also add a note in the changelog? Especially mention the removal of these APIs separately.

2023-10-25 08:21 UTC, daxpedda commented on crates/web-sys/webidls/enabled/Notification.webidl
> +  readonly attribute USVString icon;
Unfortunately we can't just introduce breaking changes like that.
```suggestion
  readonly attribute DOMString? lang;
  readonly attribute DOMString? body;
  readonly attribute DOMString? tag;
  readonly attribute USVString image;
  readonly attribute USVString? icon;
```

2023-10-25 08:21 UTC, daxpedda commented on crates/web-sys/webidls/enabled/Notification.webidl
> +  "ltr" ,
```suggestion
  "auto",
  "ltr",
```

2023-10-25 08:21 UTC, daxpedda commented on crates/web-sys/webidls/enabled/Notification.webidl
Please add a newline at the end.

2023-10-25 16:09 UTC, daxpedda requested changes

2023-10-27 09:33 UTC, Liamolucko commented
> I think removing `GetNotificationOptions`, `NotificationBehavior` and `Notification.get()` is fine though because they don't actually exist anymore. @Liamolucko and @hamza1311 would you be fine with that as well?

Yeah, I'm fine with this.

2023-10-27 12:04 UTC, hamza1311 commented
I'm fine with it. If it "breaks" any code, that code is already broken and now there is an error message for it at compile time.

2023-10-27 12:04 UTC, merged