`__wbindgen_thread_destroy` has optional params
rustwasm/wasm-bindgen pull request #3703
Opened 2023-11-12 03:55 UTC by AlexErrant

This PR updates the generated TypeScript to reflect the fact that `__wbindgen_thread_destroy` has optional params.

Ref: https://github.com/rustwasm/wasm-bindgen/blob/9fb3bca16876c756266274f78fcd0214e0581eaa/crates/threads-xform/src/lib.rs#L394-L395

Before:

```ts
export interface InitOutput {
  readonly start: () => void;
  readonly run: () => void;
  readonly child_entry_point: (a: number) => void;
  readonly memory: WebAssembly.Memory;
  readonly __wbindgen_malloc: (a: number, b: number) => number;
  readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
  readonly __wbindgen_exn_store: (a: number) => void;
  readonly __wbindgen_thread_destroy: (a: number, b: number) => void;
  readonly __wbindgen_start: () => void;
}
```

After:
```ts
export interface InitOutput {
  readonly start: () => void;
  readonly run: () => void;
  readonly child_entry_point: (a: number) => void;
  readonly memory: WebAssembly.Memory;
  readonly __wbindgen_malloc: (a: number, b: number) => number;
  readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
  readonly __wbindgen_exn_store: (a: number) => void;
  readonly __wbindgen_thread_destroy: (a?: number, b?: number) => void;
  readonly __wbindgen_start: () => void;
}
```

2023-11-14 12:05 UTC, daxpedda requested changes
This is unfortunately hacky :/

As far as I can tell we don't have more information available because we manually insert these functions into the module instead of exposing them with the `wasm_bindgen` macro. We could still actually add `wasm-bindgen` style descriptors manually to address this ... but it's questionable if that's worth it.

In any case, this is an improvement nevertheless, I don't see why not to take it.

Could you add a line to the changelog?

2023-11-15 21:59 UTC, AlexErrant commented
Also added a changelog for https://github.com/rustwasm/wasm-bindgen/pull/3690

2023-11-15 22:02 UTC, daxpedda requested changes

2023-11-15 22:02 UTC, daxpedda commented on CHANGELOG.md
> +* Update the TypeScript signature of `__wbindgen_thread_destroy` to indicate that it has optional parameters.
```suggestion

* Update the TypeScript signature of `__wbindgen_thread_destroy` to indicate that it's parameters are optional.
```

2023-11-15 22:02 UTC, daxpedda commented on CHANGELOG.md
> +* Remove experimental status from `wasm_bindgen::module()` and update docs to say it works with `--target web`.
```suggestion

* Stabilize `wasm_bindgen::module()`.
```
I don't think we ever added entries for documentation changes, so let's not start it here.

2023-11-15 22:04 UTC, merged

2023-11-15 22:05 UTC, daxpedda commented
Thank you!

2024-01-31 15:24 UTC, linonetwo commented
Hi, I'm searching for solution for #3818 

May I ask, is this renamed to `__wbindgen_free`?

2024-01-31 15:27 UTC, daxpedda commented
This function is made to destroy spawned threads, not the main instance.