use immutable buffers in SubtleCrypto methods
rustwasm/wasm-bindgen pull request #3797
Opened 2024-01-19 20:14 UTC by eric-seppanen

This change makes all the methods in `SubtleCrypto` use `&[u8]` parameters instead of `&mut [u8]`.

Here are the affected parameters:

- `decrypt(data)`: the [WebCrypto API states](https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-encrypt):
  > Let data be the result of getting a copy of the bytes held by the data parameter passed to the decrypt method.
- `digest(data)`: the [WebCrypto API states](https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-digest): 
  > Let data be the result of getting a copy of the bytes held by the data parameter passed to the digest method.
- `encrypt(data)`: the [WebCrypto API states](https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-encrypt):
  > Let data be the result of getting a copy of the bytes held by the data parameter passed to the encrypt method.
- `sign(data)`: the [WebCrypto API states](https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-sign):
  > Let data be the result of getting a copy of the bytes held by the data parameter passed to the sign method.
- `unwrapKey(wrapped_key)`: the [WebCrypto API states](https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-unwrapKey):
  > Let wrappedKey be the result of getting a copy of the bytes held by the wrappedKey parameter passed to the unwrapKey method.
- `verify(signature, data)`: the [WebCrypto API states](https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-verify):
  > Let signature be the result of getting a copy of the bytes held by the signature parameter passed to the verify method.
  > Let data be the result of getting a copy of the bytes held by the data parameter passed to the verify method.

I take the API documentation language "getting a copy of the bytes" to mean that the original buffer is left unmodified.

I can't find any evidence that these buffers would be modified. I'm not sure how strong an argument that is.

Fixes #3795.

2024-01-20 10:58 UTC, daxpedda requested changes
LGTM!
Can you add an entry in the changelog?

2024-01-22 19:11 UTC, eric-seppanen commented
Added a changelog entry.

Rebased due to merge conflicts in the changelog; I made no other changes from the previous version.

2024-01-23 08:53 UTC, daxpedda approved these changes
Thank you!

2024-01-23 08:53 UTC, merged

2024-05-31 22:53 UTC, eric-seppanen commented
I realize after the fact that this change made the 0.3.68 release not semver-compatible, because the signatures of some `SubtleCrypto` methods changed. Example: [0.3.67](https://docs.rs/web-sys/0.3.67/web_sys/struct.SubtleCrypto.html#method.verify_with_object_and_u8_array_and_buffer_source), [0.3.68](https://docs.rs/web-sys/0.3.68/web_sys/struct.SubtleCrypto.html#method.verify_with_object_and_u8_array_and_buffer_source).

Apologies for the breakage! Perhaps [cargo-semver-checks](https://github.com/obi1kenobi/cargo-semver-checks) could have caught this?

2024-06-01 06:19 UTC, daxpedda commented
AFAIK changing a parameter from `&T` to `&mut T` should not be a breaking change.

Is that what you meant or did I miss something else?

2024-06-03 17:52 UTC, eric-seppanen commented
@daxpedda Oops, you're right. (Though it's `&mut T` -> `&T`).  I confused myself by copying some code from a workspace using 0.3.68 into another project using 0.3.67 and it didn't compile. But that's not semver breakage, it's just that downgrade doesn't work. Sorry for the noise.