Fix no-std compatibility
rustwasm/wasm-bindgen pull request #4005
Opened 2024-07-04 13:12 UTC by Systemcluster

`no-std` support is currently non-functional. This PR does the following:

* Replace the unconditional `std` imports with `core` and `alloc` counterparts
* Remove most of the `if_std!` gates (`Box`, `String` and `Vec` are available in `alloc`)
* Allow exporting classes without `std`
* Add a `check --no-default-features` call to the check workflow

There are no behavioral changes. 

Note: I assume `wasm-bindgen` with `std` disabled was initially supposed to be alloc-free, but considering it hasn't been functional without `std` for a while at all, I don't think it's necessary to keep that limitation. If necessary, a separate `alloc` feature instead might make sense.

`externref`, `intern` and `take_last_exception`/`__wbindgen_exn_store` remain `std`-gated due to use of `std::thread_local!`.

2024-07-28 21:45 UTC, daxpedda requested changes
Apologies for the delay!
Thank you for doing this!

2024-07-28 21:45 UTC, daxpedda commented on src/externref.rs
> +        }
Lets use [`core::arch::wasm32::unreachable()`](https://doc.rust-lang.org/1.80.0/core/arch/wasm32/fn.unreachable.html) here instead.

2024-07-28 21:45 UTC, daxpedda commented on src/externref.rs
> +        }
Same as above.

2024-07-28 21:45 UTC, daxpedda commented on src/lib.rs
> +            }
Same as above.

2024-07-28 21:45 UTC, daxpedda commented on src/lib.rs
> +        }
I'm incredibly mindblown by this hack and very surprised its needed in the first place.
The [`no_mangle` attribute](https://doc.rust-lang.org/1.80.0/reference/abi.html?highlight=no_mangle#the-no_mangle-attribute) should imply the [`used` attribute](https://doc.rust-lang.org/1.80.0/reference/abi.html?highlight=no_mangle#the-used-attribute), addressing this issue.

Without digging into this, the best we can do is make a separate module, as described in the commend, and move `link_intrinsics()` there.

2024-07-28 21:52 UTC, daxpedda approved these changes

2024-07-28 22:14 UTC, merged

2024-07-29 14:11 UTC, Systemcluster commented
Thanks for merging!