feat: add `deviceMemory` to Navigator IDL
rustwasm/wasm-bindgen pull request #4011
Opened 2024-07-12 16:21 UTC by tltsutltsu

2024-07-12 16:31 UTC, tltsutltsu commented
The only failed CI check is [Test TypeScript output of wasm-bindgen](https://github.com/rustwasm/wasm-bindgen/pull/4011#logs), which is failing on other branches also, so I am opening this PR for review.

2024-07-28 22:27 UTC, daxpedda requested changes
Apologies for the delay!

This API should be contained in its own WebIDL file and marked as unstable.

2024-07-28 22:33 UTC, daxpedda approved these changes

2024-07-28 23:04 UTC, merged

2024-07-30 06:51 UTC, tltsutltsu commented
Thank you!