Fix negative `BigInt` formatting
rustwasm/wasm-bindgen pull request #4082
Opened 2024-08-19 21:50 UTC by ryangoree

Closes: #4081

2024-08-20 14:54 UTC, daxpedda requested changes
This needs an entry in the changelog.
Thank you!

2024-08-20 14:54 UTC, daxpedda commented on crates/js-sys/src/lib.rs
> +        )
The check `self >= &BigInt::from(0)` is being done twice now, probably the easiest thing here is to let `abs()` also return a `bool`.

2024-08-21 03:47 UTC, ryangoree commented
> This needs an entry in the changelog. Thank you!

I added an entry to the top-level changelog which seemed to be the convention, but lmk otherwise.

2024-08-21 14:50 UTC, daxpedda approved these changes
Thank you!

2024-08-21 14:50 UTC, daxpedda commented on crates/js-sys/src/lib.rs
> +    /// Returns a tuple of this BigInt's absolute value along with a boolean indicating whether the BigInt was negative.
```suggestion
    /// Returns a tuple of this [`BigInt`]'s absolute value along with a
    /// [`bool`] indicating whether the [`BigInt`] was negative.
```

2024-08-21 14:50 UTC, daxpedda commented on CHANGELOG.md
> +* Fixed negative `BigInt` values being incorrectly formatted with 2 leading dashes.
```suggestion
* Fixed negative `BigInt` values being incorrectly formatted with two minus signs.
```

2024-08-21 14:51 UTC, merged