Add Gamepad vibrationActuator API to web-sys
rustwasm/wasm-bindgen pull request #4098
Opened 2024-08-29 15:52 UTC by brettchalupa

The API that currently exists in the repo has been deprecated and the
new API has been added.

This allows gamepads to be rumbled.

I tried to follow the instructions in https://github.com/rustwasm/wasm-bindgen/tree/main/crates/web-sys#how-to-add-an-interface as best as I could.

Spec: https://w3c.github.io/gamepad/

More details: https://github.com/rustwasm/wasm-bindgen/issues/4089

It's not entirely clear to me how to best test this out, but I'm happy to if anyone's able to provide a little guidance. Thanks!

2024-09-07 15:34 UTC, daxpedda requested changes
Considering this is a working draft, these new APIs should be unstable.
This works by just moving the WebIDL to the `unstable` folder.

Otherwise this is great, thank you!

2024-09-13 18:15 UTC, brettchalupa commented
@daxpedda thanks for the guidance! I just pushed up a new commit with that change and addressed a merge conflict with the `CHANGELOG.md` file

2024-09-16 11:37 UTC, daxpedda requested changes
The CI is failing because bindings have to be regenerated.

Please let me know if you have any issues doing that or if anything is unclear!

2024-09-16 11:37 UTC, daxpedda commented on crates/web-sys/webidls/unstable/GamepadHapticActuator.webidl
> +  Promise<boolean> pulse(double value, double duration);
Already stabilized APIs can't simply be made unstable, this would be a breaking change.

2024-09-16 11:37 UTC, daxpedda commented on crates/web-sys/webidls/unstable/GamepadHapticActuator.webidl
> +};
Same as before, this can't be made unstable without a breaking change anymore.

2024-09-28 10:41 UTC, daxpedda commented
Replaced by #4134.

Turns out `hapticActuators` isn't deprecated and the Gamepad Extensions API is still valid.

2024-09-28 10:41 UTC, closed without merging