feat: add setConfiguration to RtcPeerConnection
rustwasm/wasm-bindgen pull request #4105
Opened 2024-09-06 15:02 UTC by k-wasniowski

2024-09-07 15:43 UTC, daxpedda requested changes
Missing a changelog entry.

Otherwise looks good, thank you!

2024-09-07 15:43 UTC, daxpedda commented on crates/web-sys/webidls/enabled/RTCPeerConnection.webidl
> +  undefined setConfiguration(optional RTCConfiguration configuration);
```suggestion
  [Throws]
  undefined setConfiguration(optional RTCConfiguration configuration);
```

2024-09-07 15:43 UTC, daxpedda commented on crates/web-sys/webidls/enabled/RTCPeerConnection.webidl
> +  undefined setConfiguration(optional RTCConfiguration configuration);
```suggestion
  undefined setConfiguration(optional RTCConfiguration configuration = {});
```
Following the spec es exactly as possible, to make it easier to compare it in diffs later.

2024-09-09 07:12 UTC, k-wasniowski commented
> Missing a changelog entry.
> 
> Otherwise looks good, thank you!

Thank you for your review! Updated changelog and regenerated bindings

2024-09-16 12:06 UTC, daxpedda approved these changes
Thank you!

2024-09-16 12:06 UTC, merged