Generate Symbol.dispose on classes
rustwasm/wasm-bindgen pull request #4118
Opened 2024-09-18 10:24 UTC by H-Plus-Time

Implements https://github.com/rustwasm/wasm-bindgen/issues/4117 (Explicit Resource Management support).

The main things I can think of for additional tests here are:
1. A basic Deno-only test involving `using`.
2. The polyfill mechanism (not worth it given the simplicity)

2024-09-19 12:34 UTC, daxpedda requested changes
I didn't fully review this yet, but considering its not standard yet, this should be behind an experimental flag.

Otherwise I'm happy to include this.

2024-09-19 14:34 UTC, H-Plus-Time commented
Gating behind an experimental flag I think would be more trouble than it's worth, for a few reasons:
1. At worst, it is a no-op (Symbol.dispose exists uniquely, or not at all).
2. Integrating tools (wasm-pack, basically) would need to account for said flag.
3. While the overall proposal is at stage 3, Symbol.dispose is on the far side (in the sense that the symbol name and meaning have been settled for several years).

2024-09-19 18:41 UTC, daxpedda commented
> 1. At worst, it is a no-op (Symbol.dispose exists uniquely, or not at all).

My worry is that if something changes, for whatever reason, we would need a breaking change.

> 2. Integrating tools (wasm-pack, basically) would need to account for said flag.

Indeed. We could do it via an environment variable, like many other features.

> 3. While the overall proposal is at stage 3, Symbol.dispose is on the far side (in the sense that the symbol name and meaning have been settled for several years).

Unfortunately I'm not well versed in the JS ecosystem at all, my experience so far has been that things change a lot. From the looks of it I agree that this is very unlikely to change, but I don't want to bet on it.

2024-09-19 23:27 UTC, H-Plus-Time commented
Oh, right, environment variables - yep, I'm fine with that, provided it's discoverable.

2024-09-28 08:50 UTC, daxpedda approved these changes
I explicitly added `EXPERIMENTAL` to the name and added a changelog entry.

Thank you!

2024-09-28 08:56 UTC, merged