Add support for cfg_attr for struct fields
rustwasm/wasm-bindgen pull request #4351
Opened 2024-12-11 08:45 UTC by fl0rek

closes #2703

Overview

- During #[wasm_bindgen] attribute macro expansion on struct, instead of generating ast for Program, it puts a #[derive(BindgenedStruct)] on it and preserves all the wasm_bindgen atributes as-is.
- When #[derive(BindgenedStruct)] is expanded, cfg_attr are already evaluated, so macro can just processes the leftover attributes and generate the glue code required, as it's done now. Attributes are then automatically removed by the compiler, since macro is defined as #[proc_macro_derive(BindgenedStruct, attributes(wasm_bindgen))].

2024-12-15 20:09 UTC, daxpedda requested changes
Thank you, this is a great improvement!

2024-12-15 20:09 UTC, daxpedda commented on tests/wasm/classes.rs
> +    wasm_bindgen(inspectable, js_name = "ConditionalSkipClass")
```suggestion
    wasm_bindgen(js_name = "ConditionalSkipClass")
```
Or is there some reason this is here?

2024-12-15 20:09 UTC, daxpedda commented on tests/wasm/classes.rs
> +    #[cfg_attr(target_arch = "wasm32", wasm_bindgen(skip))]
We should check on the JS side if this is properly applied.

2024-12-15 20:09 UTC, daxpedda commented on tests/wasm/classes.rs
> +    pub needs_clone: String,
We might want to say in the comment instead that this wouldn't compile otherwise, to explain how we are testing this.

2024-12-15 20:09 UTC, daxpedda commented on src/lib.rs
> +    pub use wasm_bindgen_macro::BindgenedStruct;
Lets put it in `__rt` instead. It shouldn't be visible after all.

2024-12-15 20:09 UTC, daxpedda commented on crates/macro-support/src/lib.rs
> +                    derive(wasm_bindgen::prelude::BindgenedStruct)
We have to parse the attributes to extract the `#[wasm_bindgen(wasm_bindgen = <path>)]` attribute and use it here.

2025-01-10 15:25 UTC, fl0rek reviewed
@daxpedda thanks for the review! Pushed the update after the prolonged xmas break

2025-01-11 20:30 UTC, daxpedda approved these changes
Thank you!

2025-01-11 20:31 UTC, daxpedda commented
Ah, apparently this requires a rebase! Otherwise LGTM!

2025-01-12 12:16 UTC, merged