Add options parameter to `Date.to_locale_time_string`
rustwasm/wasm-bindgen pull request #4384
Opened 2024-12-27 18:27 UTC by paul-hansen

2024-12-27 18:32 UTC, paul-hansen commented
I haven't been able to run the tests for js-sys locally when following the [contributing guide](https://rustwasm.github.io/docs/wasm-bindgen/contributing/js-sys/testing.html), getting a wasm-bindgen-cli mismatch that I can't seem to resolve even when using `cargo install -f wasm-bindgen-cli --path ../cli/ --locked` to build wasm-bindgen-cli from the repo. The tests build though 🤷

2024-12-27 18:40 UTC, paul-hansen commented
This should be marked as a breaking change since it adds a parameter to an existing function. Looks there's a label for that but I can't add labels if someone can do that for me. I'll get a changelog entry added now.

2025-01-04 15:47 UTC, daxpedda requested changes

2025-01-04 15:47 UTC, daxpedda commented on crates/js-sys/src/lib.rs
> +    pub fn to_locale_time_string(this: &Date, locale: &str, options: &JsValue) -> JsString;
Instead we can add a new method called `to_local_time_string_with_options()` that fills this gap. Making this also not a breaking change.

2025-01-04 16:05 UTC, paul-hansen commented on crates/js-sys/src/lib.rs
> +    pub fn to_locale_time_string(this: &Date, locale: &str, options: &JsValue) -> JsString;
I can do that but I should note I did it this way to match `to_locale_date_string` which takes options. Since these are related functions it would make it inconsistent to have one have a separate fn for options and one not. (Another option would be to change bith to have a with_options, but that's also breaking)

I don't have strong feelings about this personally though so just lmk how you want to handle it. Thanks!

2025-01-07 08:52 UTC, daxpedda commented on crates/js-sys/src/lib.rs
> +    pub fn to_locale_time_string(this: &Date, locale: &str, options: &JsValue) -> JsString;
I see. I was following the pattern from `web-sys` actually. But yeah, we should still stick with `*_with_options()` simply to avoid the breaking change.

Thank you for your attention on this!

2025-01-07 08:55 UTC, daxpedda commented on crates/js-sys/src/lib.rs
> +        options: &JsValue,
```suggestion
        options: Option<&Object>,
```
Is probably more accurate, again, deviating more from the `to_local_time()`. So lets just leave it for the next breaking change.

2025-01-07 08:55 UTC, daxpedda approved these changes
Thank you!

2025-01-07 08:57 UTC, merged